// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
// new tabs to be added as follows, the order to be defined as per the design
// {
//   title: '<title of the tab>',
//   url: '<router path>',
//   icon: '<ion-icon name>',
//   tab: '<tab route>',
// },
export const currencies = [
  {description: 'Albania Lek', isocode: 'ALL', symbol: 'Lek'},
  {description: 'Afghanistan Afghani', isocode: 'AFN', symbol: '؋'},
  {description: 'Argentina Peso', isocode: 'ARS', symbol: '$'},
  {description: 'Aruba Guilder', isocode: 'AWG', symbol: 'ƒ'},
  {description: 'Australia Dollar', isocode: 'AUD', symbol: '$'},
  {description: 'Azerbaijan Manat', isocode: 'AZN', symbol: '₼'},
  {description: 'Bahamas Dollar', isocode: 'BSD', symbol: '$'},
  {description: 'Barbados Dollar', isocode: 'BBD', symbol: '$'},
  {description: 'Belarus Ruble', isocode: 'BYN', symbol: 'Br'},
  {description: 'Belize Dollar', isocode: 'BZD', symbol: 'BZ$'},
  {description: 'Bermuda Dollar', isocode: 'BMD', symbol: '$'},
  {description: 'Bolivia Bolíviano', isocode: 'BOB', symbol: '$b'},
  {description: 'Bosnia and Herzegovina Convertible Mark', isocode: 'BAM', symbol: 'KM'},
  {description: 'Botswana Pula', isocode: 'BWP', symbol: 'P'},
  {description: 'Bulgaria Lev', isocode: 'BGN', symbol: 'лв'},
  {description: 'Brazil Real', isocode: 'BRL', symbol: 'R$'},
  {description: 'Brunei Darussalam Dollar', isocode: 'BND', symbol: '$'},
  {description: 'Cambodia Riel', isocode: 'KHR', symbol: '៛'},
  {description: 'Canada Dollar', isocode: 'CAD', symbol: '$'},
  {description: 'Cayman Islands Dollar', isocode: 'KYD', symbol: '$'},
  {description: 'Chile Peso', isocode: 'CLP', symbol: '$'},
  {description: 'China Yuan Renminbi', isocode: 'CNY', symbol: '¥'},
  {description: 'Colombia Peso', isocode: 'COP', symbol: '$'},
  {description: 'Costa Rica Colon', isocode: 'CRC', symbol: '₡'},
  {description: 'Croatia Kuna', isocode: 'HRK', symbol: 'kn'},
  {description: 'Cuba Peso', isocode: 'CUP', symbol: '₱'},
  {description: 'Czech Republic Koruna', isocode: 'CZK', symbol: 'Kč'},
  {description: 'Denmark Krone', isocode: 'DKK', symbol: 'kr'},
  {description: 'Dominican Republic Peso', isocode: 'DOP', symbol: 'RD$'},
  {description: 'East Caribbean Dollar', isocode: 'XCD', symbol: '$'},
  {description: 'Egypt Pound', isocode: 'EGP', symbol: '£'},
  {description: 'El Salvador Colon', isocode: 'SVC', symbol: '$'},
  {description: 'Euro Member Countries', isocode: 'EUR', symbol: '€'},
  {description: 'Falkland Islands (Malvinas) Pound', isocode: 'FKP', symbol: '£'},
  {description: 'Fiji Dollar', isocode: 'FJD', symbol: '$'},
  {description: 'Ghana Cedi', isocode: 'GHS', symbol: '¢'},
  {description: 'Gibraltar Pound', isocode: 'GIP', symbol: '£'},
  {description: 'Guatemala Quetzal', isocode: 'GTQ', symbol: 'Q'},
  {description: 'Guernsey Pound', isocode: 'GGP', symbol: '£'},
  {description: 'Guyana Dollar', isocode: 'GYD', symbol: '$'},
  {description: 'Honduras Lempira', isocode: 'HNL', symbol: 'L'},
  {description: 'Hong Kong Dollar', isocode: 'HKD', symbol: '$'},
  {description: 'Hungary Forint', isocode: 'HUF', symbol: 'Ft'},
  {description: 'Iceland Krona', isocode: 'ISK', symbol: 'kr'},
  {description: 'India Rupee', isocode: 'INR', symbol: '₹'},
  {description: 'Indonesia Rupiah', isocode: 'IDR', symbol: 'Rp'},
  {description: 'Iran Rial', isocode: 'IRR', symbol: '﷼'},
  {description: 'Isle of Man Pound', isocode: 'IMP', symbol: '£'},
  {description: 'Israel Shekel', isocode: 'ILS', symbol: '₪'},
  {description: 'Jamaica Dollar', isocode: 'JMD', symbol: 'J$'},
  {description: 'Japan Yen', isocode: 'JPY', symbol: '¥'},
  {description: 'Jersey Pound', isocode: 'JEP', symbol: '£'},
  {description: 'Kazakhstan Tenge', isocode: 'KZT', symbol: 'лв'},
  {description: 'Korea (North) Won', isocode: 'KPW', symbol: '₩'},
  {description: 'Korea (South) Won', isocode: 'KRW', symbol: '₩'},
  {description: 'Kyrgyzstan Som', isocode: 'KGS', symbol: 'лв'},
  {description: 'Laos Kip', isocode: 'LAK', symbol: '₭'},
  {description: 'Lebanon Pound', isocode: 'LBP', symbol: '£'},
  {description: 'Liberia Dollar', isocode: 'LRD', symbol: '$'},
  {description: 'Macedonia Denar', isocode: 'MKD', symbol: 'ден'},
  {description: 'Malaysia Ringgit', isocode: 'MYR', symbol: 'RM'},
  {description: 'Mauritius Rupee', isocode: 'MUR', symbol: '₨'},
  {description: 'Mexico Peso', isocode: 'MXN', symbol: '$'},
  {description: 'Mongolia Tughrik', isocode: 'MNT', symbol: '₮'},
  {description: 'Mozambique Metical', isocode: 'MZN', symbol: 'MT'},
  {description: 'Namibia Dollar', isocode: 'NAD', symbol: '$'},
  {description: 'Nepal Rupee', isocode: 'NPR', symbol: '₨'},
  {description: 'Netherlands Antilles Guilder', isocode: 'ANG', symbol: 'ƒ'},
  {description: 'New Zealand Dollar', isocode: 'NZD', symbol: '$'},
  {description: 'Nicaragua Cordoba', isocode: 'NIO', symbol: 'C$'},
  {description: 'Nigeria Naira', isocode: 'NGN', symbol: '₦'},
  {description: 'Norway Krone', isocode: 'NOK', symbol: 'kr'},
  {description: 'Oman Rial', isocode: 'OMR', symbol: '﷼'},
  {description: 'Pakistan Rupee', isocode: 'PKR', symbol: '₨'},
  {description: 'Panama Balboa', isocode: 'PAB', symbol: 'B/.'},
  {description: 'Paraguay Guarani', isocode: 'PYG', symbol: 'Gs'},
  {description: 'Peru Sol', isocode: 'PEN', symbol: 'S/.'},
  {description: 'Philippines Peso', isocode: 'PHP', symbol: '₱'},
  {description: 'Poland Zloty', isocode: 'PLN', symbol: 'zł'},
  {description: 'Qatar Riyal', isocode: 'QAR', symbol: '﷼'},
  {description: 'Romania Leu', isocode: 'RON', symbol: 'lei'},
  {description: 'Russia Ruble', isocode: 'RUB', symbol: '₽'},
  {description: 'Saint Helena Pound', isocode: 'SHP', symbol: '£'},
  {description: 'Saudi Arabia Riyal', isocode: 'SAR', symbol: '﷼'},
  {description: 'Serbia Dinar', isocode: 'RSD', symbol: 'Дин.'},
  {description: 'Seychelles Rupee', isocode: 'SCR', symbol: '₨'},
  {description: 'Singapore Dollar', isocode: 'SGD', symbol: '$'},
  {description: 'Solomon Islands Dollar', isocode: 'SBD', symbol: '$'},
  {description: 'Somalia Shilling', isocode: 'SOS', symbol: 'S'},
  {description: 'South Africa Rand', isocode: 'ZAR', symbol: 'R'},
  {description: 'Sri Lanka Rupee', isocode: 'LKR', symbol: '₨'},
  {description: 'Sweden Krona', isocode: 'SEK', symbol: 'kr'},
  {description: 'Switzerland Franc', isocode: 'CHF', symbol: 'CHF'},
  {description: 'Suriname Dollar', isocode: 'SRD', symbol: '$'},
  {description: 'Syria Pound', isocode: 'SYP', symbol: '£'},
  {description: 'Taiwan New Dollar', isocode: 'TWD', symbol: 'NT$'},
  {description: 'Thailand Baht', isocode: 'THB', symbol: '฿'},
  {description: 'Trinidad and Tobago Dollar', isocode: 'TTD', symbol: 'TT$'},
  {description: 'Turkey Lira', isocode: 'TRY', symbol: '₺'},
  {description: 'Tuvalu Dollar', isocode: 'TVD', symbol: '$'},
  {description: 'Ukraine Hryvnia', isocode: 'UAH', symbol: '₴'},
  {description: 'United Kingdom Pound', isocode: 'GBP', symbol: '£'},
  {description: 'United States Dollar', isocode: 'USD', symbol: '$'},
  {description: 'Uruguay Peso', isocode: 'UYU', symbol: '$U'},
  {description: 'Uzbekistan Som', isocode: 'UZS', symbol: 'лв'},
  {description: 'Venezuela Bolívar', isocode: 'VEF', symbol: 'Bs'},
  {description: 'Viet Nam Dong', isocode: 'VND', symbol: '₫'},
  {description: 'Yemen Rial', isocode: 'YER', symbol: '﷼'},
  {description: 'Zimbabwe Dollar', isocode: 'ZWD', symbol: 'Z$'},
];

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
