// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
// new tabs to be added as follows, the order to be defined as per the design
// {
//   title: '<title of the tab>',
//   url: '<router path>',
//   icon: '<ion-icon name>',
//   tab: '<tab route>',
// },
export const languages = [
  {description: 'English (United States)', lang: 'en-US'},
  {description: 'English (United Kingdom)', lang: 'en-GB'},
  {description: 'Afrikaans (South Africa)', lang: 'af-ZA'},
  {description: 'Albanian (Albania)', lang: 'sq-AL'},
  {description: 'Amharic (Ethiopia)', lang: 'am-ET'},
  {description: 'Arabic (Algeria)', lang: 'ar-DZ'},
  {description: 'Arabic (Bahrain)', lang: 'ar-BH'},
  {description: 'Arabic (Egypt)', lang: 'ar-EG'},
  {description: 'Arabic (Iraq)', lang: 'ar-IQ'},
  {description: 'Arabic (Israel)', lang: 'ar-IL'},
  {description: 'Arabic (Jordan)', lang: 'ar-JO'},
  {description: 'Arabic (Kuwait)', lang: 'ar-KW'},
  {description: 'Arabic (Lebanon)', lang: 'ar-LB'},
  {description: 'Arabic (Morocco)', lang: 'ar-MA'},
  {description: 'Arabic (Oman)', lang: 'ar-OM'},
  {description: 'Arabic (Qatar)', lang: 'ar-QA'},
  {description: 'Arabic (Saudi Arabia)', lang: 'ar-SA'},
  {description: 'Arabic (State of Palestine)', lang: 'ar-PS'},
  {description: 'Arabic (Tunisia)', lang: 'ar-TN'},
  {description: 'Arabic (United Arab Emirates)', lang: 'ar-AE'},
  {description: 'Arabic (Yemen)', lang: 'ar-YE'},
  {description: 'Armenian (Armenia)', lang: 'hy-AM'},
  {description: 'Azerbaijani (Azerbaijan)', lang: 'az-AZ'},
  {description: 'Basque (Spain)', lang: 'eu-ES'},
  {description: 'Bengali (Bangladesh)', lang: 'bn-BD'},
  {description: 'Bengali (India)', lang: 'bn-IN'},
  {description: 'Bosnian (Bosnia and Herzegovina)', lang: 'bs-BA'},
  {description: 'Bulgarian (Bulgaria)', lang: 'bg-BG'},
  {description: 'Burmese (Myanmar)', lang: 'my-MM'},
  {description: 'Catalan (Spain)', lang: 'ca-ES'},
  {description: 'Chinese, Cantonese (Traditional Hong Kong)', lang: 'yue-Hant-HK'},
  {description: 'Chinese, Mandarin (Simplified, China)', lang: 'zh (cmn-Hans-CN)'},
  {description: 'Chinese, Mandarin (Traditional, Taiwan)', lang: 'zh-TW (cmn-Hant-TW)'},
  {description: 'Croatian (Croatia)', lang: 'hr-HR'},
  {description: 'Czech (Czech Republic)', lang: 'cs-CZ'},
  {description: 'Danish (Denmark)', lang: 'da-DK'},
  {description: 'Dutch (Belgium)', lang: 'nl-BE'},
  {description: 'Dutch (Netherlands)', lang: 'nl-NL'},
  {description: 'English (Australia)', lang: 'en-AU'},
  {description: 'English (Canada)', lang: 'en-CA'},
  {description: 'English (Ghana)', lang: 'en-GH'},
  {description: 'English (Hong Kong)', lang: 'en-HK'},
  {description: 'English (India)', lang: 'en-IN'},
  {description: 'English (Ireland)', lang: 'en-IE'},
  {description: 'English (Kenya)', lang: 'en-KE'},
  {description: 'English (New Zealand)', lang: 'en-NZ'},
  {description: 'English (Nigeria)', lang: 'en-NG'},
  {description: 'English (Pakistan)', lang: 'en-PK'},
  {description: 'English (Philippines)', lang: 'en-PH'},
  {description: 'English (Singapore)', lang: 'en-SG'},
  {description: 'English (South Africa)', lang: 'en-ZA'},
  {description: 'English (Tanzania)', lang: 'en-TZ'},
  {description: 'English (United Kingdom)', lang: 'en-GB'},
  {description: 'English (United States)', lang: 'en-US'},
  {description: 'Estonian (Estonia)', lang: 'et-EE'},
  {description: 'Filipino (Philippines)', lang: 'fil-PH'},
  {description: 'Finnish (Finland)', lang: 'fi-FI'},
  {description: 'French (Belgium)', lang: 'fr-BE'},
  {description: 'French (Canada)', lang: 'fr-CA'},
  {description: 'French (France)', lang: 'fr-FR'},
  {description: 'French (Switzerland)', lang: 'fr-CH'},
  {description: 'Galician (Spain)', lang: 'gl-ES'},
  {description: 'Georgian (Georgia)', lang: 'ka-GE'},
  {description: 'German (Austria)', lang: 'de-AT'},
  {description: 'German (Germany)', lang: 'de-DE'},
  {description: 'German (Switzerland)', lang: 'de-CH'},
  {description: 'Greek (Greece)', lang: 'el-GR'},
  {description: 'Gujarati (India)', lang: 'gu-IN'},
  {description: 'Hebrew (Israel)', lang: 'iw-IL'},
  {description: 'Hindi (India)', lang: 'hi-IN'},
  {description: 'Hungarian (Hungary)', lang: 'hu-HU'},
  {description: 'Icelandic (Iceland)', lang: 'is-IS'},
  {description: 'Indonesian (Indonesia)', lang: 'id-ID'},
  {description: 'Italian (Italy)', lang: 'it-IT'},
  {description: 'Italian (Switzerland)', lang: 'it-CH'},
  {description: 'Japanese (Japan)', lang: 'ja-JP'},
  {description: 'Javanese (Indonesia)', lang: 'jv-ID'},
  {description: 'Kannada (India)', lang: 'kn-IN'},
  {description: 'Kazakh (Kazakhstan)', lang: 'kk-KZ'},
  {description: 'Khmer (Cambodia)', lang: 'km-KH'},
  {description: 'Korean (South Korea)', lang: 'ko-KR'},
  {description: 'Lao (Laos)', lang: 'lo-LA'},
  {description: 'Latvian (Latvia)', lang: 'lv-LV'},
  {description: 'Lithuanian (Lithuania)', lang: 'lt-LT'},
  {description: 'Macedonian (North Macedonia)', lang: 'mk-MK'},
  {description: 'Malay (Malaysia)', lang: 'ms-MY'},
  {description: 'Malayalam (India)', lang: 'ml-IN'},
  {description: 'Marathi (India)', lang: 'mr-IN'},
  {description: 'Mongolian (Mongolia)', lang: 'mn-MN'},
  {description: 'Nepali (Nepal)', lang: 'ne-NP'},
  {description: 'Norwegian Bokmål (Norway)', lang: 'no-NO'},
  {description: 'Persian (Iran)', lang: 'fa-IR'},
  {description: 'Polish (Poland)', lang: 'pl-PL'},
  {description: 'Portuguese (Brazil)', lang: 'pt-BR'},
  {description: 'Portuguese (Portugal)', lang: 'pt-PT'},
  {description: 'Punjabi (Gurmukhi India)', lang: 'pa-Guru-IN'},
  {description: 'Romanian (Romania)', lang: 'ro-RO'},
  {description: 'Russian (Russia)', lang: 'ru-RU'},
  {description: 'Serbian (Serbia)', lang: 'sr-RS'},
  {description: 'Sinhala (Sri Lanka)', lang: 'si-LK'},
  {description: 'Slovak (Slovakia)', lang: 'sk-SK'},
  {description: 'Slovenian (Slovenia)', lang: 'sl-SI'},
  {description: 'Spanish (Argentina)', lang: 'es-AR'},
  {description: 'Spanish (Bolivia)', lang: 'es-BO'},
  {description: 'Spanish (Chile)', lang: 'es-CL'},
  {description: 'Spanish (Colombia)', lang: 'es-CO'},
  {description: 'Spanish (Costa Rica)', lang: 'es-CR'},
  {description: 'Spanish (Dominican Republic)', lang: 'es-DO'},
  {description: 'Spanish (Ecuador)', lang: 'es-EC'},
  {description: 'Spanish (El Salvador)', lang: 'es-SV'},
  {description: 'Spanish (Guatemala)', lang: 'es-GT'},
  {description: 'Spanish (Honduras)', lang: 'es-HN'},
  {description: 'Spanish (Mexico)', lang: 'es-MX'},
  {description: 'Spanish (Nicaragua)', lang: 'es-NI'},
  {description: 'Spanish (Panama)', lang: 'es-PA'},
  {description: 'Spanish (Paraguay)', lang: 'es-PY'},
  {description: 'Spanish (Peru)', lang: 'es-PE'},
  {description: 'Spanish (Puerto Rico)', lang: 'es-PR'},
  {description: 'Spanish (Spain)', lang: 'es-ES'},
  {description: 'Spanish (United States)', lang: 'es-US'},
  {description: 'Spanish (Uruguay)', lang: 'es-UY'},
  {description: 'Spanish (Venezuela)', lang: 'es-VE'},
  {description: 'Sundanese (Indonesia)', lang: 'su-ID'},
  {description: 'Swahili (Kenya)', lang: 'sw-KE'},
  {description: 'Swahili (Tanzania)', lang: 'sw-TZ'},
  {description: 'Swedish (Sweden)', lang: 'sv-SE'},
  {description: 'Tamil (India)', lang: 'ta-IN'},
  {description: 'Tamil (Malaysia)', lang: 'ta-MY'},
  {description: 'Tamil (Singapore)', lang: 'ta-SG'},
  {description: 'Tamil (Sri Lanka)', lang: 'ta-LK'},
  {description: 'Telugu (India)', lang: 'te-IN'},
  {description: 'Thai (Thailand)', lang: 'th-TH'},
  {description: 'Turkish (Turkey)', lang: 'tr-TR'},
  {description: 'Ukrainian (Ukraine)', lang: 'uk-UA'},
  {description: 'Urdu (India)', lang: 'ur-IN'},
  {description: 'Urdu (Pakistan)', lang: 'ur-PK'},
  {description: 'Uzbek (Uzbekistan)', lang: 'uz-UZ'},
  {description: 'Vietnamese (Vietnam)', lang: 'vi-VN'},
  {description: 'Zulu (South Africa)', lang: 'zu-ZA'},
];

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
