export interface Task {
    taskId?:string,
    taskTitle : string,
    taskOwner :any,
    taskInitiationDate : any,
    taskEntryDate : any,
    targetCompletionDate : any,
    actualCompletionDate: any,
    taskStatus: 'OPEN',
    lastUpdateDate: any,
    subscriberId:string,
    latestComment:any,
    taskInitiator :{
      name:string,
      uid:string,
      picUrl:any,
      subscriberId:string
    },
    tags:[],
    taskProbability :string,
    taskImpact:string,
    taskMitigation:string,
    taskContingency:string,
    titleSearchMap: any,
    ownerInitiatorUidList:Array<any>,
}
